### ISSUE TITLE
Unique interface(Abstraction) for image processing. and a proxy to automatically choose available image library.

### ISSUE THREAD

**Issue by pylover** [pylover/sqlalchemy-media#101]
A unique interface for image processing purposes, I think the only thing we need is the `resize(img)->img`.

@lelit ?

**Comment by lelit** [comment]
Yes, that seems the only thing.

I can't decide on what an ideal API would be, though. 

One _easy_ option could be automatically select the available “backend” (that is, Wand, PIL, whatever), and thus exposing a `Processor` class able to delegate the job to the right _variant_.

OTOH, maybe there are cases when you want to be able to explicitly select the backend (because it happens both are present on the machine, but for whatever reason you want to use one or the other). In such case, the programmer could be allowed to explicitly use a `WandProcessor` / `PILProcessor`...

**Comment by pylover** [comment]
Yes, we already have a unique interface for images. users can specify their preferred processor(s) when defining the `Type`.

###### In addition

A Processor transparent proxy at the front of the `WandProcessor` / `PILProcessor` can solve the issue #97. 

The new processor proxy must set as default processor at all, but as I mentioned before, users can replace it.

**Comment by lelit** [comment]
Great, thank you.

**Comment by pylover** [comment]
The same process is required for analyzers.

**Comment by pylover** [comment]
![photo5890988070046641439](https://user-images.githubusercontent.com/1302253/37877344-101837da-306f-11e8-88ee-515cee3be95b.jpg)

**Comment by pylover** [comment]
Merged into master.
