### ISSUE TITLE
Consider adding dependency to python-magic-bin for Windows and Mac

### ISSUE THREAD

**Issue by jpmn** [pylover/sqlalchemy-media#115]
This fork from python-magic contains binaries for Windows and Mac: https://github.com/julian-r/python-magic. I understand that the main goal is to get rid of the python-magic dependency, but until then, it doesn't work on windows as is.

**Comment by pylover** [comment]
We cannot get rid of the `magic` because it is the main solution to detect a lot of mimetypes.

Whereas I cannot maintain and support the project in window$ because i don't have any windows installation and didn't planned to have it at all. So, if you accept the windows support responsibility, then go on with pull-requests and editing `compat.py`

**Comment by pylover** [comment]
@jpmn, Thanks for introducing the dependency condition to me, I didn't know this feature.
